services:
  db-postgres:
    hostname: db.local
    container_name: db.local
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 10
    restart: always
    environment:
      - TZ=America/Santiago
      - PGTZ=America/Santiago
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '11000:5432'
    volumes: 
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ticket_test_network

volumes:
  db_data:
    driver: local

networks:
  ticket_test_network:
    external: true